### ISSUE TITLE
Installation script

### ISSUE THREAD

**Issue by Shir0kamii** [RaitoBezarius/vimconfig#1]
I think it would be a good idea to add an installation script, because a beginner user should not know how to install it, but would want to use it since it contains a lot of useful ressources

**Comment by RaitoBezarius** [comment]
I agree, even if it may be overkill.

**Comment by Shir0kamii** [comment]
I would like to install it myself, so I think the best way to make an installation for this is to allow your configuration to blend in the already installed configuration. But it may be overkill, that's right.

**Comment by RaitoBezarius** [comment]
Hmm, it will be hard.
My vimconfig can be redundant with yours.
The best way would be to merge it manually.

And finally, the purpose of this vimconfig is to reconfigure a vim from zero.
If you want to reuse component, copy / paste them or git submodule add them.
